config/routes.rb
Rails.application.routes.draw do
  root 'statics#home'
  get 'admin/login', to: 'sessions#new', as: "login"
  post 'admin/login', to: 'sessions#create'
  get 'admin/logout', to: 'sessions#destroy', as: "logout"
  get 'admin/edit', to: 'users#edit'
  post 'admin/edit', to: 'users#update'

  resources :participants do
    collection { post :import}
  end
  resources :rewards

  get 'import', to: 'participants#import'
  post 'import', to: 'participants#import'
  get 'admin/increment', to: 'participants#inc', as: "inc"
  get 'admin/decrement', to: 'participants#dec', as: "dec"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
    require 'csv'
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30 }
    validates :points, presence: true
    validates_numericality_of :points, only_integer: true
    
    def should_generate_new_friendly_id?
       slug.blank? || name_changed?
    end
    
    def self.import(file)
        if file
            CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
                new_row = row.to_hash.delete_if { |k, v| k.nil? }
                begin
                    Participant.create(new_row)
                rescue StandardError => e
                    puts e.message
                end

            end
        end
    end
end

app/models/reward.rb
class Reward < ApplicationRecord

  has_one_attached :img

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30 }
  validates :cost, presence: true
  validates_numericality_of :cost, only_integer: true

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    include ErrorRender
    def logged_in?
       session[:user_id] != nil ? true : false
    end
    
    def authenticate_user
        if !logged_in?
            flash[:alert] = "Invalid access!"
            redirect_to "/"
        end
    end
end

app/controllers/concerns/error_render.rb
module ErrorRender
  def errors?(object)
    errors = []
    object.errors.full_messages.each do |m|
      errors << m
    end
    errors
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy, :inc, :dec]
  # before_action :authenticate_user, except: [:show]
  before_action :sanitize_amt, only: [:inc, :dec]
  
  def index
    @participants = Participant.order("points DESC")
  end

  def show
    
  end

  def new
    @participant = Participant.new
    @keywords = {
      name: "Enter",
      points: ["Enter", "Starting"],
      submit: "Create"
    }
  end
  
  def create
    @participant = Participant.new(participant_params)
    
    if @participant.save
      flash[:notice] = "Created Participant Successfully!"
      redirect_to participants_path
    else
      @errors = errors?(@participant)
      flash[:alert] = "Please correct the following errors: #{@errors.join(". ")}"
      redirect_to new_participant_path
    end
    
  end

  def edit
    @keywords = {
      name: "Edit",
      points: ["Change", "Current"],
      submit: "Update"
    }
  end
  
  def update
    if @participant.update(participant_params)
      flash[:notice] = "Updated Participant Successfully!"
      redirect_to participants_path
    else
      @errors = errors?(@participant)
      flash[:alert] = "Please correct the following errors: #{@errors.join(". ")}"
      redirect_to edit_participant_path(@participant)
    end
    
  end
  
  def destroy
    @participant.destroy
    
    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end
  
  def inc
    @participant.increment!(:points, by=@amount)
    flash[:notice] = "#{@participant.name}'s points increased by #{@amount}."
    redirect_to participants_path
  end
  
  def dec
    @participant.decrement!(:points, by=@amount)
    flash[:notice] = "#{@participant.name}'s points decreased by #{@amount}."
    redirect_to participants_path
  end

  def import
    parts = Participant.all.count
    Participant.import(params[:file])
    if Participant.all.count <= parts
      flash[:alert] = "There was an error with importing these participants. Make sure they don't already exist or that the file is in the correct format."
      redirect_to participants_path
    else
      flash[:notice] = "Participants imported!"
      redirect_to participants_path

    end


  end
  
  private
  
    def set_participant
      @participant = Participant.friendly.find(params[:id])
    end
    
    def participant_params
      params.require(:participant).permit(:name, :points)
    end
    
    def sanitize_amt
      amount = params[:amount].to_i
      @amount = amount
      puts "points #{@amount}"
    end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user, except: [:index]
  def index
    @rewards = Reward.all
  end

  def show
  end

  def new
    @reward = Reward.new
    @keywords = {
        name: "New",
        cost: ["Set", "Set"],
        submit: "Create"
    }
  end

  def create
    @reward = Reward.new(reward_params)
    # @reward.img.attach(params[:reward][:img])
    if @reward.save
      flash[:notice] = "New reward has been created!"
      redirect_to rewards_path
    else
      @errors = errors?(@reward)

      flash[:alert] = "Please correct the following errors: #{@errors.join(". ")}"
      redirect_to new_reward_path
    end
  end

  def edit
    @keywords = {
        name: "Edit",
        points: ["Change", "Current"],
        submit: "Update"
    }
  end

  def update
    if @reward.update(reward_params)
      flash[:notice] = "Reward has been updated!"
      redirect_to rewards_path
    else
      @errors = errors?(@reward)
      flash[:alert] = "Please correct the following errors: #{@errors.join(". ")}"
      redirect_to edit_reward_path(@reward)
    end
  end

  def destroy
    @reward.destroy
    flash[:notice] = "Reward has been deleted!"
    redirect_to rewards_path
  end

  private

    def reward_params
      params.require(:reward).permit(:name, :cost, :img)
    end

    def set_reward
      @reward = Reward.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:notice] = 'Logged in!'
          redirect_to participants_path
      else
          flash[:alert] = "#{user.inspect}"
          render 'new'
      end
  end

  def destroy
      session[:user_id] = nil
      flash[:notice] = 'Logged out!'
      redirect_to "/"
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
    
    def home
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  # before_action :authenticate_user
  
  def edit
    
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User Successfully Updated"
      redirect_to '/'
    else
      @errors = errors?(@user)
      flash[:alert] = "Please correct the following errors: #{@errors.join(". ")}"
      redirect_to admin_edit_path(@user)
    end
    
  end
  
  private
  
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def reward_img(object)
    if object.img.attachment
      return image_tag(url_for(object.img))
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CnEgo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/message' %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

  </body>
</html>

app/views/participants/_form.html.erb
<%= form_for @participant do |f| %>
    <p><%= f.text_field :name, placeholder: "#{@keywords[:name]} the Participant's Name", class: "form-field" %></p>
    <p><%= f.text_field :points, placeholder: "#{@keywords[:points][0]} the Participant's #{@keywords[:points][1]} points", class: "form-field" %></p>
    <p><%= f.submit "#{@keywords[:submit]} Participant", class: "form-btn" %></p>
    
<% end %>

<% if @participant.errors %>
    <% @participant.errors.full_messages.each do |m| %>
        <script type="text/javascript">
            toastr.error('<%= m %>');
        </script>
    <% end %>
<% end %>

app/views/participants/delete.js.erb
$('.delete_part').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
});  

app/views/participants/destroy.js.erb
$('.delete_part').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
        
        
        toastr.options = {
          "closeButton": false,
          "debug": false,
          "newestOnTop": false,
          "progressBar": false,
          "positionClass": "toast-top-right",
          "preventDuplicates": false,
          "onclick": null,
          "showDuration": "300",
          "hideDuration": "1000",
          "timeOut": "5000",
          "extendedTimeOut": "1000",
          "showEasing": "swing",
          "hideEasing": "linear",
          "showMethod": "fadeIn",
          "hideMethod": "fadeOut"
        }
        
        toastr["info"]("Participant has been deleted!", null);
});  

app/views/participants/edit.html.erb
<div>
  <h3>Edit Participant</h3>
  <%= render 'form', locals: {keywords: @keywords} %>
</div>

app/views/participants/index.html.erb
<div>
  <h1>All Participants [<%= link_to "New", new_participant_path %>]</h1>

  <%= form_tag import_participants_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "import CSV" %>
  <% end %>
  <br>

  <table>
      <thead>
          <th>Name</th>
          <th>Points</th>
          <th></th>
          <th>Options</th>
      </thead>
      <tbody>
          <% @participants.each do |participant| %>
              <tr>
                  <td><%= participant.name %></td>
                  <td><%= participant.points %></td>
                  <td><button id="dec-<%= participant.id %>" class="dec">-</button> <input type="text" id="points-<%= participant.id %>" placeholder="Enter a Value" value="0" class="points-field"/> <button id="inc-<%= participant.id %>" class="inc">+</button></td>
                  <td><%= link_to "View", participant_path(participant) %> | <%= link_to "Edit", edit_participant_path(participant) %> | <%= link_to "Delete", participant_path(participant), method: :delete, data: { confirm: 'Are you sure you wish to delete this participant?' }, :remote => true, :class => 'delete_part' %></td>
              </tr>
          <% end %>
      </tbody>

  </table>

  <script type="text/javascript">
      function relocate(action, id, amt) {
          window.location.replace('/admin/' + action + '?id=' + id + '&amount=' + amt);
      }

      $(".dec").click(function(){
          var id = $(this).attr('id').split('-')[1];
          relocate("decrement", id, $("#points-" + id).val());
      });

      $(".inc").click(function(){
          var id = $(this).attr('id').split('-')[1];
          relocate("increment",  id, $("#points-" + id).val());
      });
  </script>
</div>

app/views/participants/new.html.erb
<div>
  <h3>New Participant</h3>
  <%= render 'form', locals: {keywords: @keywords} %>
</div>

app/views/participants/show.html.erb
<h1><%= @participant.name %></h1>
<h3><%= @participant.points %></h3>

app/views/rewards/_form.html.erb
<%= form_for @reward do |f| %>
  <p><%= f.text_field :name, placeholder: "#{@keywords[:name]} the Reward's Name", class: "form-field" %></p>
  <p><%= f.text_field :cost, placeholder: "#{@keywords[:cost][0]} the Reward's #{@keywords[:cost][1]} cost", class: "form-field" %></p>
  <p><%= f.file_field :img,
                      multiple: false,
                      direct_upload: true,
                      options: { class: "form-btn" } %></p>
  <p><%= f.submit "#{@keywords[:submit]} Reward", class: "form-btn" %></p>

<% end %>

app/views/rewards/index.html.erb
<div>
  <h1>All Rewards [<%= link_to "New", new_reward_path %>]</h1>

  <br>

  <table>
    <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td>
          <p><%= reward_img(reward) %></p>
          <p><%= reward.name %> (Costs: <%= reward.cost %>)</p>
          <p><%= link_to "View", reward_path(reward) %> | <%= link_to "Edit", edit_reward_path(reward) %>
            | <%= link_to "Delete", reward_path(reward), method: :delete, data: { confirm: 'Are you sure you wish to delete this reward?' } %> </p>
        </td>
      </tr>
    <% end %>
    </tbody>

  </table>
</div>

app/views/rewards/new.html.erb
<div>
  <h3>New Reward</h3>
  <%= render 'form', locals: {keywords: @keywords} %>
</div>

app/views/rewards/show.html.erb
<div>
  <h3><%= @reward.name %></h3>
  <p><%= reward_img(@reward) %></p>
  <h4><%= @reward.cost %></h4>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul>
    <li>
      <%= link_to "About iAppreciate WApp", root_path %>
    </li>
    <li>
      <%= link_to "About Stormhelm Company" %>
    </li>
    <li>
      <%= link_to "Report an Issue", "https://www.google.com" %>
    </li>
  </ul>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <h2>iAppreciate</h2>
</div>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
    <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>', '', {"closeButton": false, "debug": false, "positionClass": "toast-top-right", "onclick": null, "showDuration": "300", "hideDuration": "1000", "timeOut": "5000", "extendedTimeOut": "1000", "showEasing": "swing", "hideEasing": "linear", "showMethod": "fadeIn", "hideMethod": "fadeOut" });
    <% end %>
</script>
<% end %>

app/views/statics/home.html.erb
<div>
  <h3>Welcome to the iAppreciate Web Hub</h3>
  <h4>Curious how many points you've earned?</h4>
  You can easily check your current points by navigating to "iappreciate.io/your-name".
  <p>or</p>
  <h4>Know how many points you have and want to spend them?</h4>
  Visit the reward catalogue by <%= link_to "Clicking Here", root_path %>
</div>

app/views/users/edit.html.erb
<div>
  <%= form_for @user do |f| %>
      <p><%= f.text_field :name, placeholder: "Enter a Name", class: "form-field" %></p>
      <p><%= f.text_field :email, placeholder: "Enter an Email", class: "form-field" %></p>
      <p><%= f.password_field :password, placeholder: "Enter a new Password", class: "form-field" %></p>
      <p><%= f.password_field :password_confirmation, placeholder: "Reenter new Password", class: "form-field" %></p>
      <%= f.submit "Update", class: "form-btn" %>
  <% end %>
</div>